//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoe_Project_V2.Model.Model_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis_Detay
    {
        public int ID { get; set; }
        public Nullable<int> urunid { get; set; }
        public int satisid { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<int> tutar { get; set; }
    
        public virtual Satislar Satislar { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
